<?php

namespace DoctrineProxies\__CG__\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entities\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'document', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'names', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'cellphone', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'auth0Id', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'wallet', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'transactions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'document', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'names', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'email', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'cellphone', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'auth0Id', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'wallet', '' . "\0" . 'App\\Entities\\Client' . "\0" . 'transactions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', []);

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocument(string $document): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocument', [$document]);

        return parent::setDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getNames(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNames', []);

        return parent::getNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setNames(string $names): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNames', [$names]);

        return parent::setNames($names);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCellphone(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCellphone', []);

        return parent::getCellphone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCellphone(string $cellphone): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCellphone', [$cellphone]);

        return parent::setCellphone($cellphone);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuth0Id(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuth0Id', []);

        return parent::getAuth0Id();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuth0Id(?string $auth0Id): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuth0Id', [$auth0Id]);

        return parent::setAuth0Id($auth0Id);
    }

    /**
     * {@inheritDoc}
     */
    public function getWallet(): ?\App\Entities\Wallet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWallet', []);

        return parent::getWallet();
    }

    /**
     * {@inheritDoc}
     */
    public function setWallet(?\App\Entities\Wallet $wallet): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWallet', [$wallet]);

        return parent::setWallet($wallet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactions', []);

        return parent::getTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\App\Entities\Transaction $transaction): \App\Entities\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', [$transaction]);

        return parent::addTransaction($transaction);
    }

}
